#!/usr/bin/env python3
"""
Generate actual Sigil test code for stdlib modules using Samael/Infernum
Usage: ./generate_stdlib_tests.py <module_name>
"""

import sys
import json
import subprocess
import re

STDLIB = "/home/crook/dev/sigil-lang/parser/src/stdlib.rs"
INFERNUM_URL = "http://127.0.0.1:8081/v1/chat/completions"

def extract_module(module_name: str) -> str:
    """Extract the register_<module> function from stdlib.rs"""
    with open(STDLIB, 'r') as f:
        content = f.read()

    pattern = rf'^fn register_{module_name}\(interp: &mut Interpreter\) \{{'
    match = re.search(pattern, content, re.MULTILINE)
    if not match:
        return ""

    start = match.start()
    depth = 0
    in_string = False
    i = match.end() - 1

    for j, c in enumerate(content[i:], i):
        if c == '"' and (j == 0 or content[j-1] != '\\'):
            in_string = not in_string
        if not in_string:
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    return content[start:j+1]

    lines = content[start:].split('\n')[:200]
    return '\n'.join(lines)

def call_infernum(code: str, module: str) -> str:
    """Generate Sigil test code using Infernum"""

    system_prompt = """You are Samael, an expert test generator for the Sigil programming language.

Generate actual runnable Sigil test code (not just specs). Sigil uses these conventions:
- `rite` instead of `fn` for functions
- `≔` instead of `let` for variable bindings
- `yea`/`nay` instead of true/false
- `⎇`/`⎉` instead of if/else
- `#[test]` attribute for test functions
- `assert!()`, `assert_eq!()` for assertions

Output format: Generate a complete Sigil test scroll (module) with test functions.
Example:
```sigil
#[cfg(test)]
scroll math_tests {
    #[test]
    rite test_abs_positive() {
        assert_eq!(abs(5), 5);
        assert_eq!(abs(5.0), 5.0);
    }

    #[test]
    rite test_abs_negative() {
        assert_eq!(abs(-5), 5);
        assert_eq!(abs(-5.0), 5.0);
    }
}
```

Focus on:
- Test edge cases (zero, negative, very large numbers)
- Test type handling (int vs float)
- Test error conditions with invalid inputs
- Use descriptive test names"""

    user_prompt = f"""Generate Sigil test code for these stdlib functions:

```rust
{code[:3500]}
```

Generate a complete test scroll with at least 15-20 test functions covering:
1. Basic functionality (positive cases)
2. Edge cases (zero, negative numbers, very large values)
3. Type coercion (int to float, etc.)
4. Error handling (invalid inputs should error)

Output ONLY the Sigil code, no explanations."""

    request = {
        "model": "Qwen/Qwen2.5-7B-Instruct",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.2,
        "max_tokens": 4096
    }

    result = subprocess.run(
        ["curl", "-s", "-X", "POST", INFERNUM_URL,
         "-H", "Content-Type: application/json",
         "-d", json.dumps(request)],
        capture_output=True, text=True, timeout=300
    )

    response = json.loads(result.stdout)
    return response.get('choices', [{}])[0].get('message', {}).get('content', '')

def main():
    module = sys.argv[1] if len(sys.argv) > 1 else "math"

    print(f"// Auto-generated Sigil tests for stdlib::{module}")
    print(f"// Generated by Samael using Infernum (Qwen2.5-7B)")
    print()

    code = extract_module(module)
    if not code:
        print(f"// Error: Could not find register_{module} in stdlib.rs")
        sys.exit(1)

    result = call_infernum(code, module)

    # Clean up the output - extract just the Sigil code
    if "```sigil" in result:
        result = result.split("```sigil")[1].split("```")[0]
    elif "```" in result:
        result = result.split("```")[1].split("```")[0]

    print(result.strip())

if __name__ == "__main__":
    main()
