//! Sigil actor skeleton generation from `EguiMigrationSpec`.
//!
//! Produces a `.sigil` file for each spec, with:
//! - `invoke qliphoth·prelude·*;` header
//! - `☉ ᛈ ActorMsg { }` message enum (outside actor, if messages exist)
//! - Actor state fields with evidentiality sigils
//! - `on Variant { }` message handler stubs
//! - `rite new()` constructor stub
//! - `rite view()` skeleton with `??MARKER??` annotations where needed
//!
//! The output is intentionally incomplete — `??MARKER??` annotations mark
//! locations that require manual attention after generation.

use super::patterns::vnode_for_pattern;
use super::spec::{EguiMigrationSpec, EguiRecommendations, TargetPattern};

// =============================================================================
// Output type
// =============================================================================

/// A generated `.sigil` file.
#[derive(Debug, Clone)]
pub struct GeneratedSigil {
    /// Suggested output path (relative), e.g. `"sigil/src/notifications.sigil"`.
    pub path: String,
    /// Full text content of the generated file.
    pub code: String,
    /// The actor/struct name this was generated for.
    pub actor_name: String,
}

// =============================================================================
// Entry point
// =============================================================================

/// Generate a `.sigil` skeleton from a migration spec.
pub fn generate_sigil(spec: &EguiMigrationSpec) -> GeneratedSigil {
    let mut code = String::new();

    // Header
    code.push_str(&format!(
        "invoke qliphoth·prelude·*;\n\
         \n\
         // Source: {} (egui→Qliphoth migration — review all ??MARKER?? annotations)\n\
         // Generated by: sigil migrate --from-egui\n\
         // automation_score: {:.2}  complexity: {:?}\n",
        spec.source.path,
        spec.automation_score,
        spec.complexity,
    ));

    // Ambiguity summary at top if any exist
    if !spec.ambiguities.is_empty() {
        code.push_str(&format!(
            "// {} ambiguit{} require manual review:\n",
            spec.ambiguities.len(),
            if spec.ambiguities.len() == 1 { "y" } else { "ies" }
        ));
        for amb in &spec.ambiguities {
            code.push_str(&format!(
                "//   ??{}?? (line {}) — {}\n",
                amb.kind, amb.line, amb.snippet
            ));
        }
    }

    code.push('\n');

    match spec.target.pattern {
        TargetPattern::Actor  => code.push_str(&generate_actor(spec)),
        TargetPattern::Function => code.push_str(&generate_function(spec)),
    }

    GeneratedSigil {
        path: spec.target.suggested_path.clone(),
        code,
        actor_name: spec.name.clone(),
    }
}

// =============================================================================
// Actor generation
// =============================================================================

fn generate_actor(spec: &EguiMigrationSpec) -> String {
    let mut s = String::new();

    // Message enum goes OUTSIDE the actor block (☉ ᛈ ActorMsg)
    if !spec.recommendations.messages.is_empty() {
        s.push_str(&generate_msg_enum(spec));
        s.push('\n');
    }

    s.push_str(&format!("actor {} {{\n", spec.name));

    // State fields
    if !spec.recommendations.state_fields.is_empty() {
        s.push_str("    // State\n");
        for field in &spec.recommendations.state_fields {
            s.push_str(&format!(
                "    {}: {}{}\n",
                field.name,
                field.field_type,
                field.evidentiality,
            ));
        }
        s.push('\n');
    }

    // on handlers (one stub per message variant)
    if !spec.recommendations.messages.is_empty() {
        for msg in &spec.recommendations.messages {
            let variant_with_payload = match &msg.payload {
                Some(p) => format!("{}(_payload: {})", msg.name, p),
                None    => msg.name.clone(),
            };
            s.push_str(&format!(
                "    on {} {{\n        // ??TODO?? — {}\n    }}\n\n",
                variant_with_payload,
                msg.description,
            ));
        }
    }

    // new() constructor
    s.push_str(&generate_new(spec));
    s.push('\n');

    // view() rite
    s.push_str(&generate_view(spec));

    s.push_str("}\n");
    s
}

/// Generate a `☉ ᛈ ActorMsg { }` enum to be placed before the actor block.
fn generate_msg_enum(spec: &EguiMigrationSpec) -> String {
    let mut s = String::new();
    s.push_str(&format!("☉ ᛈ {}Msg {{\n", spec.name));
    for msg in &spec.recommendations.messages {
        match &msg.payload {
            Some(p) => s.push_str(&format!("    {}({}),\n", msg.name, p)),
            None    => s.push_str(&format!("    {},\n", msg.name)),
        }
    }
    s.push_str("}\n");
    s
}

fn generate_new(spec: &EguiMigrationSpec) -> String {
    let mut s = String::new();
    s.push_str(&format!("    rite new() -> {}! {{\n", spec.name));
    s.push_str(&format!("        {} {{\n", spec.name));

    for field in &spec.recommendations.state_fields {
        let default = default_value_for(&field.field_type);
        s.push_str(&format!("            {}: {},\n", field.name, default));
    }

    s.push_str("        }\n");
    s.push_str("    }\n");
    s
}

/// Generate `rite view() -> VNode!` with pattern-translated body.
/// Ambiguous patterns emit `??MARKER??` comments in-place.
fn generate_view(spec: &EguiMigrationSpec) -> String {
    let mut s = String::from("    rite view() -> VNode! {\n");
    s.push_str("        // ??GENERATED — review all ??MARKER?? annotations below??\n");

    if spec.ambiguities.is_empty() {
        s.push_str("        div()\n");
        s.push_str(&format!(
            "            ·class(\"{}-root\")\n",
            to_kebab_case(&spec.name)
        ));
        s.push_str("            ·to_vnode()\n");
    } else {
        // Emit ambiguity stubs inline
        s.push_str("        div()\n");
        s.push_str(&format!(
            "            ·class(\"{}-root\")\n",
            to_kebab_case(&spec.name)
        ));
        for amb in &spec.ambiguities {
            s.push_str(&format!(
                "            // ??{}?? line {} — {}\n",
                amb.kind, amb.line, amb.snippet
            ));
        }
        s.push_str("            ·to_vnode()\n");
    }

    s.push_str("    }\n");
    s
}

// =============================================================================
// Pure function generation (for simple helpers)
// =============================================================================

fn generate_function(spec: &EguiMigrationSpec) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/// {}  (pure helper — migrated from egui)\n",
        spec.name
    ));
    s.push_str(&format!(
        "rite {}() -> VNode! {{\n",
        to_snake_case(&spec.name)
    ));
    s.push_str("    // ??GENERATED??\n");
    s.push_str("    div()·to_vnode()\n");
    s.push_str("}\n");
    s
}

// =============================================================================
// Helpers
// =============================================================================

fn default_value_for(type_str: &str) -> &'static str {
    match type_str {
        t if t.starts_with("Vec<")    => "vec![]",
        t if t.starts_with("Option<") => "None",
        t if t.starts_with("HashMap<")=> "HashMap·new()",
        t if t.starts_with("String")  => "String·new()",
        "bool"                         => "false",
        "usize" | "u8" | "u16" | "u32" | "u64" => "0",
        "isize" | "i8" | "i16" | "i32" | "i64" => "0",
        "f32" | "f64"                  => "0.0",
        _                              => "Default·default()",
    }
}

fn to_kebab_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('-');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::migrate::egui::spec::*;

    fn make_simple_spec(name: &str) -> EguiMigrationSpec {
        EguiMigrationSpec {
            id: format!("test.rs:{}", name),
            name: name.to_string(),
            source: EguiSource {
                path: "test.rs".to_string(),
                code: String::new(),
            },
            target: EguiTarget {
                suggested_path: format!("sigil/src/test.sigil"),
                pattern: TargetPattern::Actor,
            },
            recommendations: EguiRecommendations {
                state_fields: vec![
                    EguiStateField {
                        name: "count".to_string(),
                        field_type: "usize".to_string(),
                        evidentiality: "!".to_string(),
                    }
                ],
                messages: vec![
                    EguiMessage {
                        name: "Increment".to_string(),
                        payload: None,
                        description: "Increment count".to_string(),
                    }
                ],
            },
            ambiguities: vec![],
            automation_score: 0.9,
            complexity: Complexity::Simple,
            complexity_factors: vec![],
            status: MigrationStatus::Pending,
        }
    }

    #[test]
    fn test_generate_actor_contains_actor_keyword() {
        let spec = make_simple_spec("Counter");
        let gen = generate_sigil(&spec);
        assert!(gen.code.contains("actor Counter {"));
    }

    #[test]
    fn test_generate_has_invoke() {
        let spec = make_simple_spec("Foo");
        let gen = generate_sigil(&spec);
        assert!(gen.code.contains("invoke qliphoth·prelude·*;"));
    }

    #[test]
    fn test_generate_state_field() {
        let spec = make_simple_spec("Bar");
        let gen = generate_sigil(&spec);
        assert!(gen.code.contains("count: usize!"));
    }

    #[test]
    fn test_generate_msg_enum() {
        let spec = make_simple_spec("Baz");
        let gen = generate_sigil(&spec);
        // Enum is now a top-level ☉ ᛈ BazMsg { } outside the actor block
        assert!(gen.code.contains("☉ ᛈ BazMsg {"), "missing ☉ ᛈ BazMsg in:\n{}", gen.code);
        assert!(gen.code.contains("Increment,"), "missing Increment variant");
        // Must NOT have enum Msg inside actor
        assert!(!gen.code.contains("enum Msg {"), "enum Msg {{}} inside actor is invalid Sigil");
    }

    #[test]
    fn test_msg_enum_before_actor() {
        let spec = make_simple_spec("Counter");
        let gen = generate_sigil(&spec);
        let enum_pos = gen.code.find("☉ ᛈ CounterMsg").expect("missing enum");
        let actor_pos = gen.code.find("actor Counter {").expect("missing actor");
        assert!(enum_pos < actor_pos, "☉ ᛈ CounterMsg must appear before actor Counter block");
    }

    #[test]
    fn test_on_handler_stubs_in_actor() {
        let spec = make_simple_spec("Counter");
        let gen = generate_sigil(&spec);
        assert!(gen.code.contains("on Increment {"), "missing on handler in:\n{}", gen.code);
    }
}
